name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules.
        run: yarn
      - name: Build 'src'.
        run: yarn build
      - name: Build 'electron'.
        run: yarn build-electron
