name: Draft Release

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  draft-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: sudo apt-get install --no-install-recommends -y libarchive-tools libopenjp2-tools rpm
      - run: npm install
      - run: GH_TOKEN="${{ secrets.WORKFLOW_TOKEN }}" npm run ci-build
